### ISSUE TITLE
CEFR level of a native speaker?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-omobilities#19]
Nomination includes information about student's language skills. We use a CEFR level each language. However, can CEFR level be used to describe a native speaker?

The C2 CEFR level is defined as "Nearly native-speaker level". Is it "proper" to use C2 for native speakers?

@erasmus-without-paper/all-members

**Comment by EvelienRenders** [comment]
@wrygiel 
It is possible to be technically a native speaker (= you acquired the language by exposure in the early years of your life) and yet to be well below CEFR C2 in terms your ability to actually use the language "even in the most complex situations" (as the C2 level is defined). It's rare but it happens, such as when the language is one you spoke at home when you were little but didn't speak it in school and haven't used it since. This is called incomplete acquisition in sociolinguistic circles.

In other words, your language skills and your status as a native speaker are separate categories. One does not necessarily imply the other. I see nothing wrong or dishonest with using the CEFR scale to describe language skills in your mother tongue. The only possible problem is that the CEFR scale was designed with learners in mind and probably doesn't go as high as native speakers are able to go.

So short answer: Yes, you should use C2 as the level for native speakers as well as for people who have achieved a learned mastery of the language, also called bilingualism.

**Comment by wrygiel** [comment]
Thanks! I'm no longer working on this, but it's always good to close an old GitHub issue :) I guess there might be many similar ones here.
